version: 'version'


services:
  mysql:
    image: mysql:9.1.0
    container_name: crudDB
    ports:
      -"3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="admin"
      - MYSQL_DATABASE="cruddatabase"
      - MYSQL_USER="root"
      - MYSQL_PASSWORD="admin"
    volumes:
      -mysql_data:/var/lib/mysql
    networks:
      - crudnetwork
    
